Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202502.21.0"

  config.vm.network "private_network", ip: "192.168.56.11"
  
  config.vm.network "forwarded_port", guest: 3000, host: 3000  
  config.vm.network "forwarded_port", guest: 8000, host: 8000  

  config.vm.provider "virtualbox" do |vb|
    vb.name = "booklibrary-vm"
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provision "app", type: "shell", path: "scripts/app.sh", privileged: true
  config.vm.provision "setup-nginx", type: "shell", path: "scripts/setup-nginx.sh", privileged: true
  config.vm.provision "main", type: "shell", path: "scripts/verificar-servicios.sh", privileged: true

  config.vm.post_up_message = <<-MSG
🔴 ¡Book Library VM lista!
======================================
📱 90 Days of DevOps by Roxs 🚀
MSG
end
