#SPDX-License-Identifier: MIT-0
---
# tasks file for user

- name: Crear usuario devops
  user:
    name: "{{ user }}"
    groups: sudo
    append: yes
    password: "{{ password | password_hash('sha512') }}"
