---
- name: Instalar dependencias de Node.js para Result
  community.general.npm:
    path: "{{ app_base_path }}/{{ app_base_name }}/result"
    state: present
      #ci: yes

- name: Crear script de inicio para Node.js Result con PM2
  shell: |
    pm2 start main.js --name result-app -- -p {{ result_app_port }}
    pm2 save
  args:
    chdir: "{{ app_base_path }}/{{ app_base_name }}/result"
    executable: /bin/bash
  environment:
    APP_PORT: "{{ result_app_port }}"
    DATABASE_HOST: "{{ pg_host }}"
    DATABASE_USER: "{{ pg_user }}"
    DATABASE_PASSWORD: "{{ pg_password }}"
    DATABASE_NAME: "{{ pg_db }}"
    DATABASE_PORT: "{{ pg_port }}"
  become_user: "{{ ansible_user }}"

...
