---
- name: Instalar dependencias de Node.js para Worker
  community.general.npm:
    path: "{{ app_base_path }}/{{ app_base_name }}/worker"
    state: present
    # Añadir esto para asegurar la instalación sin interacción
    #ci: yes

- name: Crear script de inicio para Node.js Worker con PM2
  shell: |
    pm2 start main.js --name worker-app
    pm2 save
  args:
    chdir: "{{ app_base_path }}/{{ app_base_name }}/worker"
    executable: /bin/bash
  environment:
    DATABASE_HOST: "{{ pg_host }}"
    DATABASE_USER: "{{ pg_user }}"
    DATABASE_PASSWORD: "{{ pg_password }}"
    DATABASE_NAME: "{{ pg_db }}"
    REDIS_HOST: "{{ redis_host }}"
    REDIS_PORT: "{{ redis_port }}"
    PGPORT: "{{ pg_port }}"
  become_user: vagrant

- name: Asegurar que PM2 esté configurado para iniciar al arranque
  shell: |
    pm2 startup systemd -u vagrant --hp /home/vagrant
    pm2 save
  args:
    executable: /bin/bash
  become: yes

...
