Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202502.21.0"

  config.vm.network "private_network", ip: "192.168.56.10"
  
#  config.vm.network "forwarded_port", guest: 80, host: 80  

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ansible-devops-vm"
    vb.memory = "2048"
    vb.cpus = 2
  end

   # Provisionamiento con Shell
  config.vm.provision "shell", inline: <<-SHELL
    echo "¡Hola desde el provisionamiento!" > /tmp/hola.txt
  SHELL

  config.vm.synced_folder ".", "/vagrant"

  # Provisionamiento con Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbooks/playbook.yml"
    ansible.verbose = "v"
  end
  

 # config.vm.provision "setup-system", type: "shell", path: "scripts/setup-system.sh", privileged: true
 # config.vm.provision "setup-backend", type: "shell", path: "scripts/setup-backend.sh", privileged: false
 # config.vm.provision "setup-frontend", type: "shell", path: "scripts/setup-frontend.sh", privileged: false
 # config.vm.provision "setup-nginx", type: "shell", path: "scripts/setup-nginx.sh", privileged: true
 # config.vm.provision "setup-start", type: "shell", path: "scripts/setup-start.sh", privileged: false
  config.vm.post_up_message = <<-MSG
🔴 ¡ANSIBLE DevOps VM lista!
======================================
📱 90 Days of DevOps by Roxs 🚀
MSG
end
