Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 3001, host: 3001 # app result
  config.vm.network "forwarded_port", guest: 3000, host: 3000 # app worker metrics
  config.vm.network "forwarded_port", guest: 5000, host: 80 # app vote
  
  # Provisionamiento con Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.verbose = "v"

    ansible.inventory_path = "ansible/inventario/hosts" # Le dice a Vagrant que use tu inventario
    ansible.limit = "192.168.56.10"            # Limita a la IP específica que está en tu inventario y grupo
                                               # (o puedes usar ansible.limit = "webservers" si tu playbook apunta a 'all')
    ansible.config_file = "ansible/ansible.cfg"
    # Esto le dice a Ansible que use el archivo de configuración SSH generado por Vagrant. 
    # vagrant ssh-config > ansible/inventario/ssh_config_for_ansible
    #ansible.ssh_args = [ "-F", "ansible/inventario/ssh_config_for_ansible" ]
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devops-voting-app-vm"
    vb.memory = "2048" # 4GB de RAM
    vb.cpus = 1        # 2 núcleos de CPU
  end

#  config.vm.provision "setup-system", type: "shell", path: "scripts/app.sh", privileged: true

  config.vm.post_up_message = <<-MSG
    🔴 ¡VM APP aplicacion lista!
    ======================================
    📱 90 Days of DevOps by Roxs 🚀
  MSG
end
