#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx


- name: Instalar nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Habilitar y arrancar Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Copiar landing page estilo hacker desde plantilla
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
