---
# Variables generales del sistema
#dependencies: ["python3", "python3-pip", "python3-venv", "curl", "python3-psycopg2", "redis"]
system_packages:
  - git
  - curl
  - build-essential
  - python3
  - python3-pip
  - python3-venv
  - python3-virtualenv
  - python3-psycopg2 
  - postgresql-client
  - net-tools
  - acl

# Configuración de PostgreSQL
pg_version: "14"
pg_user: "postgres"
pg_password: "postgres"
pg_db: "votes"
pg_host: "127.0.0.1"
pg_port: 5432


# Configuración de Redis
redis_port: 6379
redis_host: "127.0.0.1"

# Configuración de Node.js (para Worker y Result)
node_version: "18.x"
pm2_version: "latest"

# Rutas de la aplicación
repo: https://github.com/roxsross/roxs-devops-project90.git
app_base_path: /home/vagrant/app
app_base_name: roxs-voting-app

# Puertos de los servicios (accedidos desde el host)
vote_app_port: 5000 # Gunicorn/Flask en Vote
worker_app_port: 3000 # Puerto del Worker (para métricas, si aplica)
result_app_port: 3001 # App Node.js en Result
...
