---
# Variables generales del sistema
#dependencies: ["python3", "python3-pip", "python3-venv", "curl", "python3-psycopg2", "redis"]
system_packages:
  - git
  - curl
  - build-essential
  - python3
  - python3-pip
  - python3-venv
  - postgresql-client
  - net-tools

# Configuraci贸n de PostgreSQL
pg_version: "14"
pg_user: "dbuser"
pg_password: "dbpassword"
pg_db: "votingapp"

# Configuraci贸n de Redis
redis_port: 6379

# Configuraci贸n de Node.js (para Worker y Result)
node_version: "18.x"
pm2_version: "latest"

# Rutas de la aplicaci贸n
app_base_path: /opt/app

# Puertos de los servicios (accedidos desde el host)
vote_app_port: 5000
worker_app_port: 8001 # Gunicorn/Flask en Vote
result_app_port: 8000 # App Node.js en Result
...
